### ISSUE TITLE
Broken in Neovim after rewrite

### ISSUE THREAD

**Issue by 4513ECHO** [machakann/vim-highlightedundo#10]
After rewrite this plugin requires `+job` feature and `job_start()` function, but Neovim does not have it.

Cloud you support Neovim again?

FYI: Neovim has `vim.diff()` function in Lua. Please consider use it if you will support Neovim.

**Comment by machakann** [comment]
PR is welcome. Maybe, it is required to switch [`s:system()`](https://github.com/machakann/vim-highlightedundo/blob/1111d951ddf6216e228379d522c2530e7aa291ca/autoload/highlightedundo.vim#L242-L250) and [`s:diff()`](https://github.com/machakann/vim-highlightedundo/blob/1111d951ddf6216e228379d522c2530e7aa291ca/autoload/highlightedundo.vim#L205-L216) between cases?
