### ISSUE TITLE
Not working with ViM-8.0.0

### ISSUE THREAD

**Issue by ratheesh** [machakann/vim-highlightedundo#2]
This plugin works fine with neovim-0.2.2 but does not with work with ViM-8.0.0

My configuration:

let g:highlightedundo#highlight_mode = 2
nmap u     <Plug>(highlightedundo-undo)
nmap <C-r> <Plug>(highlightedundo-redo)
nmap U     <Plug>(highlightedundo-Undo)
nmap g-    <Plug>(highlightedundo-gminus)
nmap g+    <Plug>(highlightedundo-gplus)

**Comment by machakann** [comment]
Thanks! Did you get any error message? Is an external `diff` command available in both environments? Check the output of the following command `:echomsg executable('diff')`

**Comment by ratheesh** [comment]
sorry for late reply.
Yes, external `diff` command is available. I tested both vim and neovim in same machine.

**Comment by ratheesh** [comment]
I tested with latest vim stable release `ViM-8.0.1428`. With this, the plugin works fine as expected.
Thanks for your support.

**Comment by machakann** [comment]
That's fine!
